;;; keybindings
(global-set-key (kbd "C-x <left>") 'windmove-left)
(global-set-key (kbd "C-x <right>") 'windmove-right)
(global-set-key (kbd "C-x <up>") 'windmove-up)
(global-set-key (kbd "C-x <down>") 'windmove-down)
(global-set-key (kbd "C-c <up>")   'previous-error)
(global-set-key (kbd "C-c <down>") 'next-error)
(global-set-key (kbd "C-c o")      'ff-find-other-file)
(global-set-key (kbd "C-h C-g")    'gtk-lookup-symbol)
(global-set-key (kbd "<M-return>") 'align-current)
(global-set-key (kbd "<f1>") 'ido-find-file)
(global-set-key (kbd "<f2>") 'ido-switch-buffer)
(global-set-key (kbd "<f3>") 'save-buffer)
(global-set-key (kbd "<f4>") 'eval-buffer)
(global-set-key (kbd "<f8>") 'display-line-numbers-mode)
(global-set-key (kbd "<f12>") 'compile)
(global-set-key (kbd "M-TAB") 'completion-at-point)
(global-set-key (kbd "C-M-<down>")    #'enlarge-window)
(global-set-key (kbd "C-M-<up>")  #'shrink-window)
(global-set-key (kbd "C-M-<left>") #'enlarge-window-horizontally)
(global-set-key (kbd "C-M-<right>")  #'shrink-window-horizontally)
(global-set-key (kbd "s-c") 'clipboard-kill-ring-save)
(global-set-key (kbd "s-v") 'clipboard-yank)

(provide 'keybinds)

